wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.4
    framework: xgboost
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.5
    start_time: 1667377590.07251
    t:
      1:
      - 2
      - 3
      - 55
      2:
      - 2
      - 3
      - 5
      - 6
      - 53
      - 55
      3:
      - 3
      - 8
      - 23
      4: 3.8.5
      5: 0.13.4
      8:
      - 1
      - 3
      - 5
      10:
      - 9
